import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Typography, Button, useTheme, Box } from "@mui/material";

export default function Home() {
  const theme = useTheme();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={{ ...theme.layout.displayMiddle }}>
          <Button variant="outlined" sx={{ color: "red" }}>
            Outlined
          </Button>
          <Typography variant="s48_w700" color="red">
            11
          </Typography>
        </Box>
      </main>
    </>
  );
}
